[package]
name = "brujeria"
version = "0.1.2"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
enum-iterator = "1.0"
enum-unitary = "0.5"
colored = "2.0.0"